"""
Django settings for stashcast project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import sys
from pathlib import Path

import environ

env = environ.Env(
    # set casting, default value
    DEBUG=(bool, False)
)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Take environment variables from .env file
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('DEBUG', default=True)

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS')

CSRF_TRUSTED_ORIGINS = env.list('CSRF_TRUSTED_ORIGINS', default=[])

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https') 

print("ALLOWED_HOSTS:", ALLOWED_HOSTS)
print("CSRF_TRUSTED_ORIGINS:", CSRF_TRUSTED_ORIGINS)
print("SECURE_PROXY_SSL_HEADER:", SECURE_PROXY_SSL_HEADER)
print("SERVICE_URL_CADDY:", env('SERVICE_URL_CADDY', default=''))


# Application definition

INSTALLED_APPS = [
    'media',  # Must be before admin to override templates
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'huey.contrib.djhuey',
    'bx_django_utils',
    'huey_monitor',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    # "whitenoise.middleware.WhiteNoiseMiddleware",
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'stashcast.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'media.context_processors.stashcast_settings',
            ],
        },
    },
]

WSGI_APPLICATION = 'stashcast.wsgi.application'

STASHCAST_DATA_DIR = Path(os.environ.get('STASHCAST_DATA_DIR', BASE_DIR / 'data'))
STASHCAST_MEDIA_DIR = STASHCAST_DATA_DIR / 'media'


os.environ['NLTK_DATA'] = os.environ.get('NLTK_DATA', str(STASHCAST_DATA_DIR))

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': STASHCAST_DATA_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

# Language code from environment variable (e.g., 'en', 'en-us', 'es')
# This sets the UI language and the language for video subtitles/transcripts
LANGUAGE_CODE = os.environ.get('LANGUAGE_CODE', 'en-us')

# Supported languages
LANGUAGES = [
    ('en', 'English'),
    ('es', 'Español'),
    ('pt', 'Português'),
]

# Path to translation files
LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

TIME_ZONE = os.environ.get('TIME_ZONE', 'UTC')

USE_I18N = True

USE_TZ = True

# Extract the primary language code for yt-dlp subtitles (e.g., 'en' from 'en-us')
# This will be used to download subtitles/transcripts in the configured language
STASHCAST_SUBTITLE_LANGUAGE = LANGUAGE_CODE.split('-')[0]

# Validate that the configured language is supported
SUPPORTED_LANGUAGE_CODES = [code for code, name in LANGUAGES]
# Allow both primary codes (e.g., 'en') and regional variants (e.g., 'en-us')
PRIMARY_LANGUAGE = LANGUAGE_CODE.split('-')[0]
if (
    PRIMARY_LANGUAGE not in SUPPORTED_LANGUAGE_CODES
    and LANGUAGE_CODE not in SUPPORTED_LANGUAGE_CODES
):
    raise ValueError(
        f"Unsupported LANGUAGE_CODE: '{LANGUAGE_CODE}'. "
        f'Supported languages: {", ".join(SUPPORTED_LANGUAGE_CODES)}. '
        f'Set LANGUAGE_CODE environment variable to one of the supported languages.'
    )


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Directory where collectstatic will collect static files for production
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# STASHCAST Configuration

STASHCAST_USER_TOKEN = env('STASHCAST_USER_TOKEN')

# Require user token for RSS feeds (set to 'true' to enable)
REQUIRE_USER_TOKEN_FOR_FEEDS = (
    os.environ.get('REQUIRE_USER_TOKEN_FOR_FEEDS', 'false').lower() == 'true'
)

# Optional environment variables
STASHCAST_MEDIA_BASE_URL = os.environ.get('STASHCAST_MEDIA_BASE_URL', None)

# Default yt-dlp args optimized for mobile playback
# Audio: AAC codec in M4A container is widely supported
# Metadata is embedded directly into the media file
# Subtitles are converted to VTT format by yt-dlp
# Note: --embed-thumbnail removed because it deletes the thumbnail file after embedding.
# We need the thumbnail file for grid view and RSS feed artwork.
# Note: --convert-thumbnails removed due to yt-dlp race condition causing
# FileNotFoundError when FFmpeg tries to convert before file is ready.
# Thumbnails are converted to PNG in process_files() after download completes.
STASHCAST_DEFAULT_YTDLP_ARGS_AUDIO = os.environ.get(
    'STASHCAST_DEFAULT_YTDLP_ARGS_AUDIO',
    '--audio-format m4a --audio-quality 128K --embed-metadata --convert-subs vtt',
)

# Video: H.264/AAC in MP4 container for maximum mobile compatibility
# Limit to 720p to balance quality and file size
# Format filter: prefer best video ≤720p + best audio, fallback to combined format ≤720p
# Metadata is embedded, subtitles converted to VTT and embedded
# Note: --embed-thumbnail and --convert-thumbnails removed (see audio args comment above)
STASHCAST_DEFAULT_YTDLP_ARGS_VIDEO = os.environ.get(
    'STASHCAST_DEFAULT_YTDLP_ARGS_VIDEO',
    '--format "bv*[height<=720][vcodec^=avc]+ba/b[height<=720]" '
    '--merge-output-format mp4 '
    '--embed-metadata '
    '--convert-subs vtt --embed-subs',
)

# FFmpeg args for transcoding (if needed)
STASHCAST_DEFAULT_FFMPEG_ARGS_AUDIO = os.environ.get(
    'STASHCAST_DEFAULT_FFMPEG_ARGS_AUDIO', '-c:a aac -b:a 128k'
)

STASHCAST_DEFAULT_FFMPEG_ARGS_VIDEO = os.environ.get(
    'STASHCAST_DEFAULT_FFMPEG_ARGS_VIDEO',
    '-c:v libx264 -preset fast -crf 23 -c:a aac -b:a 128k -movflags +faststart',
)

STASHCAST_SLUG_MAX_WORDS = int(os.environ.get('STASHCAST_SLUG_MAX_WORDS', '6'))
STASHCAST_SLUG_MAX_CHARS = int(os.environ.get('STASHCAST_SLUG_MAX_CHARS', '40'))
STASHCAST_SUMMARY_SENTENCES = int(os.environ.get('STASHCAST_SUMMARY_SENTENCES', '8'))

# Optional: Proxy URL for yt-dlp requests
# Use residential proxy to avoid YouTube blocking cloud VM IPs
# Formats: http://host:port, socks5://host:port, socks5://user:pass@host:port
# See docs/YOUTUBE_AUTH.md for setup instructions
STASHCAST_YTDLP_PROXY = os.environ.get('STASHCAST_YTDLP_PROXY', None)

# Podcast Index API credentials (optional, for podcast RSS feed discovery)
# Get free API keys at: https://podcastindex.org/
PODCAST_INDEX_API_KEY = os.environ.get('PODCAST_INDEX_API_KEY', None)
PODCAST_INDEX_API_SECRET = os.environ.get('PODCAST_INDEX_API_SECRET', None)

# Spotify URL handling: auto-select first search result (no user input needed)
STASHCAST_ACCEPT_FIRST_MATCH = os.environ.get('STASHCAST_ACCEPT_FIRST_MATCH', '').lower() in (
    'true',
    '1',
    'yes',
)

# Optional: Maximum number of episodes (READY status) to keep
# When the limit is reached, new downloads are blocked until episodes are deleted
# 0 or unset = unlimited
STASHCAST_MAX_EPISODES = int(os.environ.get('STASHCAST_MAX_EPISODES', '0'))

# Ensure media directories exist
os.makedirs(STASHCAST_MEDIA_DIR, exist_ok=True)

# Media files configuration
MEDIA_URL = '/media/'
MEDIA_ROOT = STASHCAST_MEDIA_DIR

# Huey configuration (SQLite backend)

HUEY = {
    'huey_class': 'huey.SqliteHuey',
    'name': 'stashcast',
    'filename': str(STASHCAST_DATA_DIR / 'huey.db'),
    'immediate': 'test' in sys.argv
    or 'pytest' in sys.modules,  # Execute tasks immediately during tests
    'consumer': {
        'workers': 2,
        'worker_type': 'thread',
    },
}
