# Generated by Django 6.0 on 2026-01-01 00:42

import media.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaItem',
            fields=[
                ('guid', models.CharField(default=media.models.generate_nanoid, editable=False, max_length=21, primary_key=True, serialize=False)),
                ('source_url', models.URLField(max_length=2048)),
                ('slug', models.SlugField(max_length=100)),
                ('media_type', models.CharField(blank=True, choices=[('audio', 'Audio'), ('video', 'Video')], max_length=10)),
                ('requested_type', models.CharField(choices=[('auto', 'Auto'), ('audio', 'Audio'), ('video', 'Video')], max_length=10)),
                ('status', models.CharField(choices=[('PREFETCHING', 'Prefetching'), ('DOWNLOADING', 'Downloading'), ('PROCESSING', 'Processing'), ('READY', 'Ready'), ('ERROR', 'Error')], db_index=True, default='PREFETCHING', max_length=20)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True)),
                ('author', models.CharField(blank=True, max_length=200)),
                ('publish_date', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('extractor', models.CharField(blank=True, max_length=100)),
                ('external_id', models.CharField(blank=True, max_length=200)),
                ('webpage_url', models.URLField(blank=True, max_length=2048)),
                ('base_dir', models.CharField(blank=True, max_length=500)),
                ('content_path', models.CharField(blank=True, max_length=500)),
                ('thumbnail_path', models.CharField(blank=True, max_length=500)),
                ('subtitle_path', models.CharField(blank=True, max_length=500)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('log_path', models.CharField(blank=True, max_length=500)),
                ('error_message', models.TextField(blank=True)),
                ('ytdlp_args', models.TextField(blank=True, help_text='Additional yt-dlp arguments')),
                ('ffmpeg_args', models.TextField(blank=True, help_text='Additional ffmpeg arguments')),
                ('summary', models.TextField(blank=True)),
                ('downloaded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-publish_date', '-downloaded_at'],
                'indexes': [models.Index(fields=['source_url'], name='media_media_source__2bf5fe_idx'), models.Index(fields=['slug'], name='media_media_slug_21be11_idx'), models.Index(fields=['status'], name='media_media_status_8448b7_idx'), models.Index(fields=['media_type'], name='media_media_media_t_ea723f_idx')],
            },
        ),
    ]
