# Generated by Django 6.0.7 on 2026-07-26 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0005_mediagroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediagroup',
            name='image',
            field=models.ImageField(blank=True, help_text="Optional cover image shown as <image> in this group's RSS feed.", null=True, upload_to='group-images'),
        ),
    ]
